SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

Create VIEW [dbo].[vw_SMS_UNION_Checkline]
as
SELECT  [CheckLineUID]
      ,[ShiftID]
      ,[CheckUID]
      ,[CashCheckLineNo]
      ,[SectionID]
      ,[ScaleUID]
      ,[ScalePropertyUID]
      ,[ArticleUID]
      ,[BasePrice]
      ,[Quantity]
      ,[BaseSum]
      ,[Discount]
      ,[Replace]
      ,[Operation]
      ,[SalesPersonID]
      ,[LinkedCashCheckNo]
      ,[LinkedCheckUID]
      ,[id_tt_cl]
      ,[id_tov_cl]
      ,[date_ch]
      ,[time_ch]
      ,[OperationType_cl]
      ,[znak]
      ,[CheckLineID]
      ,[LoadDateTime_cl]
      ,[id_sms_tovar]
      ,[date_add]
      ,[Price_retail]
      ,[id_kontr]
      ,[BonusCard_cl]
      ,[id_coupons_type2_card_tov]
      ,[id_lovepr_card_tov]
      ,[id_discount_chl]
      ,[set_price]
      ,[green_price]
  FROM  [SRV-SQL01].[SMS_UNION].[dbo].[Checkline] as chl 
GO